### ISSUE TITLE
Can't make it work ! :(

### ISSUE THREAD

**Issue by AurelienVernay** [a-h-abid/lumen-ng4-quickstart#1]
Hello, i wanted to use your ng4 + lumen quickstart project for a university project but i can't make it work :(
After cloning, installing composer and npm dependencies, and serving all in a wamp directory, i can access public folder and load index.html page, but i get 404 not found on all zone.js, shim.js and system.js files.

![image](https://user-images.githubusercontent.com/18377871/34495377-30a60e9c-eff5-11e7-9517-07444429c1d1.png)

And the angular app therefore doesn't boot.

What am i doing wrong ?

Regards,

**Comment by a-h-abid** [comment]
Did you tried with `php artisan serve` ? This way should work and should be easy n quick to start.

The reason the scripts getting 404 is because they are not looking from the subdirectory, rather they are looking from the document root of localhost. In your case might be `C:\wamp\www`.

Running laravel / lumen in subfolder is a bit complicated. You can google how to run laravel / lumen in a subfolder for WAMP / XAMPP. And in laravel community, it is recommended to set Document Root to `/public` folder for your host server. It is a bit longer process but generally you have to add a custom virtual host in your apache with document root set to `public` folder, add that host to `C:\Windows\System32\drivers\etc\hosts`, restart apache service and then visit your custom host in your browser.

Edit: I forgot that `artisan serve` was removed from Lumen. You can follow [this answer](https://stackoverflow.com/a/34702610/1414178) to get this feature in Lumen. Another way is using `php -S localhost:8000 -t public`.
